engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
languages:
  JavaScript: true
exclude_paths:
  - "node_modules/"