export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_IS_API_CALL_IN_PROGRESS = 'SET_API_CALL_IN_PROGRESS';
export const SET_HOME_PAGE_FORM = 'SET_HOME_PAGE_FORM';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const SET_TODOLISTS = 'SET_TODOLISTS';
export const ADD_TODOLIST = 'ADD_TODOLIST';
